name: Stop VM
description: Shut down the QEMU VM container after testing completes.
inputs:
  container-name:
    description: Name of the container hosting the VM.
    required: true
  qemu-monitor-addr:
    description: Address used by the QEMU monitor.
    required: false
    default: 127.0.0.1:45454
  qemu-pidfile:
    description: Path used for the QEMU pidfile inside the container.
    required: false
    default: /tmp/qemu-ci.pid
runs:
  using: composite
  steps:
    - name: Stop VM container
      shell: bash
      env:
        CONTAINER_NAME: ${{ inputs.container-name }}
        QEMU_MONITOR_ADDR: ${{ inputs.qemu-monitor-addr }}
        QEMU_PIDFILE: ${{ inputs.qemu-pidfile }}
      run: ./scripts/ci/stop-vm.sh
