name: Smoke Test
description: Run QEMU smoke testing and validate VGA output using a running VM.
inputs:
  container-name:
    description: Name of the container hosting the running VM.
    required: true
  qemu-monitor-addr:
    description: Address used by the QEMU monitor.
    required: false
    default: 127.0.0.1:45454
  vnc-port:
    description: VNC port used for smoke testing.
    required: false
    default: "1"
  vnc-connect-addr:
    description: Host address used by VNC tooling to connect to QEMU.
    required: false
    default: 127.0.0.1
runs:
  using: composite
  steps:
    - name: Run smoke test
      shell: bash
      env:
        CONTAINER_NAME: ${{ inputs.container-name }}
        QEMU_MONITOR_ADDR: ${{ inputs.qemu-monitor-addr }}
        VNC_PORT: ${{ inputs.vnc-port }}
        VNC_CONNECT_ADDR: ${{ inputs.vnc-connect-addr }}
      run: ./scripts/ci/smoke-test.sh
