name: Integration Test
description: Run integration tests and capture VNC snapshots.
inputs:
  qemu-monitor-addr:
    description: Address used by the QEMU monitor.
    required: false
    default: 127.0.0.1:45454
  vnc-port:
    description: VNC port used for integration testing.
    required: false
    default: "1"
  vnc-connect-addr:
    description: Host address used by VNC tooling to connect to QEMU.
    required: false
    default: 127.0.0.1
runs:
  using: composite
  steps:
    - name: Run integration tests
      shell: bash
      run: |
        docker run --rm \
          -e QEMU_MONITOR_ADDR="${{ inputs.qemu-monitor-addr }}" \
          -e VNC_PORT="${{ inputs.vnc-port }}" \
          -e VNC_CONNECT_ADDR="${{ inputs.vnc-connect-addr }}" \
          -v "$PWD":/src \
          -w /src \
          enzos-run \
          bash -c '
            set -euo pipefail

            export VNC_SCREENSHOT=qemu-screen-integration.ppm
            export VNC_CLIENT_LOG=qemu-vnc-client-integration.log
            export QEMU_PIDFILE=/tmp/qemu-integration.pid
            export QEMU_KEEP_ALIVE=true
            export QEMU_VNC_LOG=qemu-vnc-server-integration.log
            export VNC_PORT="${VNC_PORT:-1}"
            export VNC_CONNECT_ADDR="${VNC_CONNECT_ADDR:-127.0.0.1}"

            ./scripts/qemu-smoketest.sh enzos.iso

            go test ./scripts -count=1 -v

            ./scripts/capture-vnc.sh

            export VNC_SCREENSHOT=qemu-screen-integration-terminal.ppm
            export VNC_CLIENT_LOG=qemu-vnc-client-integration-terminal.log
            export VNC_WAIT_SECONDS=3

            ./scripts/capture-vnc.sh

            go run ./scripts/cmd/qemu_monitor_client -mode exec -addr "${QEMU_MONITOR_ADDR:-127.0.0.1:45454}" -cmd quit || true
          '
