name: Integration Test
description: Run integration tests and capture VNC snapshots against a running VM.
inputs:
  container-name:
    description: Name of the container hosting the running VM.
    required: true
  qemu-pidfile:
    description: Path used for the QEMU pidfile inside the container.
    required: false
    default: /tmp/qemu-ci.pid
  qemu-monitor-addr:
    description: Address used by the QEMU monitor.
    required: false
    default: 127.0.0.1:45454
  vnc-port:
    description: VNC port used for integration testing.
    required: false
    default: "1"
  vnc-connect-addr:
    description: Host address used by VNC tooling to connect to QEMU.
    required: false
    default: 127.0.0.1
runs:
  using: composite
  steps:
    - name: Run integration tests
      shell: bash
      run: |
        set -euo pipefail

        docker exec \
          -w /src \
          -e QEMU_MONITOR_ADDR="${{ inputs.qemu-monitor-addr }}" \
          -e QEMU_PIDFILE="${{ inputs.qemu-pidfile }}" \
          -e VNC_PORT="${{ inputs.vnc-port }}" \
          -e VNC_CONNECT_ADDR="${{ inputs.vnc-connect-addr }}" \
          "${{ inputs.container-name }}" bash -c '
          set -euo pipefail

          export QEMU_MONITOR_ADDR="${QEMU_MONITOR_ADDR:-${{ inputs.qemu-monitor-addr }}}"
          export QEMU_PIDFILE="${QEMU_PIDFILE:-${{ inputs.qemu-pidfile }}}"
          export VNC_PORT="${VNC_PORT:-${{ inputs.vnc-port }}}"
          export VNC_CONNECT_ADDR="${VNC_CONNECT_ADDR:-${{ inputs.vnc-connect-addr }}}"
          export QEMU_KEEP_ALIVE=true
          export QEMU_VNC_LOG=qemu-vnc-server-integration.log
          export VNC_WAIT_SECONDS=${VNC_WAIT_SECONDS:-2}

          capture_integration_images() {
            set +e

            echo "[integration-test] Replaying echo scenario so the terminal screenshot reflects the shell exercise." >&2
            go test ./scripts -count=1 -run TestShellEchoCommand -v -test.timeout=1m \
              >/tmp/integration-terminal-setup.log 2>&1 || \
              echo "[integration-test] Unable to replay echo scenario; screenshot may not show expected prompt." >&2

            local default_wait="${VNC_WAIT_SECONDS:-2}"

            export VNC_SCREENSHOT=qemu-screen-integration.ppm
            export VNC_CLIENT_LOG=qemu-vnc-client-integration.log
            export VNC_WAIT_SECONDS="$default_wait"
            ./scripts/capture-vnc.sh || true

            export VNC_SCREENSHOT=qemu-screen-integration-terminal.ppm
            export VNC_CLIENT_LOG=qemu-vnc-client-integration-terminal.log
            export VNC_WAIT_SECONDS=3
            ./scripts/capture-vnc.sh || true

            set -e
          }

          go run ./scripts/cmd/qemu_monitor_client -mode wait -addr "$QEMU_MONITOR_ADDR" -timeout 15s

          if [[ -n "$QEMU_PIDFILE" && ! -f "$QEMU_PIDFILE" ]]; then
            echo "QEMU pidfile missing at $QEMU_PIDFILE; cannot run integration tests." >&2
            exit 1
          fi

          if ! kill -0 "$(cat "$QEMU_PIDFILE")" 2>/dev/null; then
            echo "QEMU process not running after boot (pidfile: $QEMU_PIDFILE)." >&2
            exit 1
          fi

          set +e
          go test ./scripts -count=1 -v -test.timeout=5m
          test_status=$?
          set -e

          trap capture_integration_images EXIT

          exit "$test_status"
        '
