name: Start VM
description: Boot QEMU in a long-running container for downstream tests.
inputs:
  container-name:
    description: Name assigned to the container hosting the VM.
    required: true
  qemu-monitor-addr:
    description: Address used by the QEMU monitor.
    required: false
    default: 127.0.0.1:45454
  vnc-port:
    description: VNC port used for the running VM.
    required: false
    default: "1"
  qemu-pidfile:
    description: Path used to persist the QEMU pidfile inside the container.
    required: false
    default: /tmp/qemu-ci.pid
runs:
  using: composite
  steps:
    - name: Start VM container
      shell: bash
      env:
        CONTAINER_NAME: ${{ inputs.container-name }}
        QEMU_MONITOR_ADDR: ${{ inputs.qemu-monitor-addr }}
        QEMU_PIDFILE: ${{ inputs.qemu-pidfile }}
        VNC_PORT: ${{ inputs.vnc-port }}
      run: ./scripts/ci/start-vm-container.sh
